name = "etch"
version = "1.0.0"
description = "A Gleam TUI Backend Library"
licences = ["MIT"]
repository = { type = "github", user = "bananaofhappiness", repo = "https://github.com/bananaofhappiness/etch" }

internal_modules = [
  "etch/internal",
  "etch/internal/*",
  "examples/*",
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
